# CONFIGURA\u00c3\u0087\u00c3\u0083O DO MYSQL - BIBLIOTECH
# Se o MySQL estiver usando outra porta, altere 3306.
# O par\u00c3\u00a2metro createDatabaseIfNotExist cria o schema caso o usu\u00c3\u00a1rio tenha permiss\u00c3\u00a3o.
db.url=jdbc:mysql://localhost:3306/bibliotech
db.user=root
db.password=1234